### ISSUE TITLE
Download as a CSV

### ISSUE THREAD

**Issue by umagnanasundaram2128** [umagnanasundaram2128/SimplyClip#10]
- [x]  Add button for download CSV
- [x] Align the button in the popup
- [x] Capture the link from which the text is copied
- [x] Maintain the original copied text and edited text
- [x] Implement Download CSV functionality with data

**Comment by niveditalodha** [comment]
Is the URL for a specific text added in the CSV?

**Comment by umagnanasundaram2128** [comment]
yes, the URL in CSV is for the link from which the text is copied.
