### ISSUE TITLE
Blurred simply clip icon in the header of the extension

### ISSUE THREAD

**Issue by vamshi-chidara** [umagnanasundaram2128/SimplyClip#12]
On clicking the extension, the icon of simply clip in the header is blurred.

**Comment by niveditalodha** [comment]
Can we also change the extension icon which is visible in the tab section. It is using the previous icon but we have updated it in the extension UI

**Comment by akhilkumarmengani** [comment]
Yes, I have changed the extension icons and replaced the blurred icon in the UI as well.

**Comment by akhilkumarmengani** [comment]
@niveditalodha @vamshi-chidara Please close the issue if everything looks correct.

**Comment by vamshi-chidara** [comment]
Yeah looks good. Closing the issue now.
