### ISSUE TITLE
new text added using add button disappears after reopening the extension

### ISSUE THREAD

**Issue by niveditalodha** [umagnanasundaram2128/SimplyClip#16]

**Comment by niveditalodha** [comment]
Can you check this storage issue? @akhilkumarmengani

**Comment by niveditalodha** [comment]
@vamshi-chidara @akhilkumarmengani  any update on this?

**Comment by umagnanasundaram2128** [comment]
@niveditalodha  Resolved this issue. Please check it and close the issue.

**Comment by niveditalodha** [comment]
Issue is resolved. Closing it!!
