### ISSUE TITLE
Expand text area in edit mode

### ISSUE THREAD

**Issue by akhilkumarmengani** [umagnanasundaram2128/SimplyClip#17]
When a user click on edit item, text area should be resized to larger size which enables user to see more text.

**Comment by akhilkumarmengani** [comment]
<img width="408" alt="textarea-editmode" src="https://user-images.githubusercontent.com/70975566/139604058-13488232-c769-4bf6-b773-81393cf701ac.png">

Attached image contains text area which is not resized in edit mode.

**Comment by niveditalodha** [comment]
Check the edit text area and close it if working well.

**Comment by niveditalodha** [comment]
This enhancement is complete. Closing this issue
