### ISSUE TITLE
CSV button hover issue

### ISSUE THREAD

**Issue by akhilkumarmengani** [umagnanasundaram2128/SimplyClip#22]
When cursor is hovered over add button ,CSV button is also getting transitioned. Since CSV button is not being selected, it should not transition.

**Comment by akhilkumarmengani** [comment]
@vamshi-chidara  please look into the issue

**Comment by vamshi-chidara** [comment]
I will look into it.

**Comment by vamshi-chidara** [comment]
Resolved the transition issue. Please have a look and let me know if its fine
https://github.com/umagnanasundaram2128/SimplyClip/commit/7b9f1c40fadc55d2fe7421dd602967b3c06e2d83

**Comment by niveditalodha** [comment]
Closing this issue. Working fine
