### ISSUE TITLE
Add Button - adds new empty list item

### ISSUE THREAD

**Issue by akhilkumarmengani** [umagnanasundaram2128/SimplyClip#9]

**Comment by vamshi-chidara** [comment]
Added button to the extension so that user can add an empty text box to the list and write his own notes.
[https://github.com/umagnanasundaram2128/SimplyClip/commit/80fee9719bd06c9883162974511df57202879123](url)

**Comment by umagnanasundaram2128** [comment]
This feature works fine. Closing this issue.
